runtime: python39
service: nhl-commentary

# Scaling configuration
basic_scaling:
  max_instances: 10
  idle_timeout: 10m

# Resource configuration
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20

# Environment variables
env_variables:
  FLASK_ENV: production

# Static file handlers
handlers:
- url: /static
  static_dir: static
  secure: always
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: always

- url: /.*
  script: auto
  secure: always

# Network settings
network:
  session_affinity: true

# Skip files for deployment
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?tests$
- ^(.*/)?test_.*\.py$
- ^Dockerfile$
- ^\.dockerignore$
- ^\.git.*$
- ^\.env$
- docs/ 